name: Get Latest Ancestor Tag

description: Get the latest ancestor tag of the current commit.

inputs:
  current-tag:
    description: The current publishing tag
    required: true

outputs:
  latest-tag:
    description: "The latest tag"
    value: ${{ steps.get-tag.outputs.latest-tag }}

runs:
  using: composite
  steps:
    - name: get latest ancestor tag
      id: get-ancestor-tag
      shell: bash
      run: |
        set -e
        pwd
        ANCESTOR_TAG=$(git describe --tags --exclude=${{ inputs.current-tag }} --abbrev=0 2>/dev/null)
        echo "ANCESTOR_TAG=$ANCESTOR_TAG"
        echo "ANCESTOR_TAG=$ANCESTOR_TAG" >> $GITHUB_ENV

    - name: get latest tag from api
      id: get-latest-tag-from-api
      shell: bash
      run: |
        REPO="${{ github.repository }}"
        LATEST_TAG=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" \
          | jq -r 'if type == "object" then .tag_name else null end')
        if [ "$LATEST_TAG" = "null" ] || [ "$LATEST_TAG" = "${{ inputs.current-tag }}" ]; then
          LATEST_TAG=$(echo "$RELEASES_RESPONSE" \
            | jq -r --arg CURRENT "$CURRENT_TAG" \
              'if type == "array" then
                  .[] | select(
                    .draft == false and 
                    .tag_name != $CURRENT and 
                    .tag_name != null
                  ) | .tag_name
                else
                  null
                end' \
            | head -n 1)
        fi
        if [ "$LATEST_TAG" = "null" ] || [ -z "$LATEST_TAG" ]; then
          LATEST_TAG=""
        fi
        echo "LATEST_TAG=$LATEST_TAG"
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - id: get-tag
      shell: bash
      run: |
        if [ -n "${{ env.ANCESTOR_TAG }}" ]; then
          FINAL_TAG="${{ env.ANCESTOR_TAG }}"
        else
          FINAL_TAG="${{ env.LATEST_TAG }}"
        fi

        echo "Latest tag found: $FINAL_TAG"
        echo "latest-tag=$FINAL_TAG" >> $GITHUB_OUTPUT
