# Uncomment the next line to define a global platform for your project
platform :osx, '12.0'
project 'SVGMetaRenderer.xcodeproj'

target 'SVGMetaRenderer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SVGMetaRenderer
  # Note: ServalSVG podspec is currently iOS-only, so we'll configure dependencies manually in Xcode
  # For now, we'll configure the header search paths and source files directly in Xcode

end
