# frozen_string_literal: true

source "https://rubygems.org"

# Common tools for iOS projects
# - CocoaPods: iOS dependency management
# - Fastlane: CI/release automation
# - xcpretty: beautify Xcode build logs
# - dotenv: load environment variables from .env
# - cocoapods-deintegrate / cocoapods-clean: clean up Pod-related files

gem "cocoapods"
gem "xcodeproj"
