project 'ServalMarkdownDemo.xcodeproj'
platform :ios, '12.0'
target 'ServalMarkdownDemo' do
  pod 'ServalMarkdown', :path => '../../../'
  pod 'LynxTextra', :path => '../../../third_party/lynx-textra'
end
