name: sync dependencies

description: pull common source and binary dependencies via habitat.

inputs:
  concurrency:
    description: concurrency of requests
    default: "2"
    required: false
  cache-backend:
    description: cache backend for habitat
    default: "lynx-infra"
    required: false
  target:
    description: habitat target
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: setup cache action
      if: ${{ inputs.cache-backend == 'github' }}
      uses: actions/cache@v4
      with:
        path: ~/.habitat_cache
        key: hab-${{ runner.os }}-${{ hashFiles('.habitat', 'DEPS') }}
        restore-keys: |
          hab-${{ runner.os }}-

    - name: install Python dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          python3 -m pip install PyYAML --break-system-packages
          python3 -m pip install requests --break-system-packages
        else
          python3 -m pip install PyYAML
          python3 -m pip install requests
        fi

    - name: run habitat sync
      shell: bash
      run: |
        source tools/envsetup.sh
        if [[ "${{ inputs.target }}" == "" ]]; then
          ./hab sync .
        else
          ./hab sync . --target ${{ inputs.target }}
        fi
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
